# Generated by Django 4.1.2 on 2022-11-01 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='whatsappclone/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_contacts',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='message_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='message_timer',
            field=models.CharField(choices=[('24 HOURS', '24 HOURS'), ('7 DAYS', '7 DAYS'), ('90 DAYS', '90 DAYS'), ('OFF', 'OFF')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='read_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_previews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_reaction_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sounds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('LIGHT', 'LIGHT'), ('DARK', 'DARK'), ('SYSTEM_DEFAULT', 'SYSTEM_DEFAULT')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to='whatsappclone/wallpapers/'),
        ),
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockee_blocked_contacts', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocker_blocked_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
