# Generated by Django 4.1.2 on 2022-11-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], default='EVERYONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], default='EVERYONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_status',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], default='EVERYONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.CharField(choices=[('EVERYONE', 'EVERYONE'), ('MY CONTACTS', 'MY CONTACTS'), ('NOBODY', 'NOBODY')], default='EVERYONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_timer',
            field=models.CharField(choices=[('24 HOURS', '24 HOURS'), ('7 DAYS', '7 DAYS'), ('90 DAYS', '90 DAYS'), ('OFF', 'OFF')], default='OFF', max_length=100),
        ),
    ]
