# Generated by Django 4.1.2 on 2022-11-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_about_status_alter_user_avatar_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blockedcontact',
            constraint=models.UniqueConstraint(fields=('blocker', 'blockee'), name='unique_blocker_blockee'),
        ),
    ]
