# Generated by Django 4.1.2 on 2022-11-11 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='whatsappclonev1/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to='whatsappclonev1/wallpapers/'),
        ),
    ]
