# Generated by Django 4.1.2 on 2022-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_is_online_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('LIGHT', 'LIGHT'), ('DARK', 'DARK'), ('SYSTEM_DEFAULT', 'SYSTEM_DEFAULT')], default='DARK', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='whatsappclonev1/wallpapers/'),
        ),
    ]
